-- Migration: reseed feats + backfill origin_feat_name
-- Generated from db/seed/srd/feats.json and db/seed/srd/backgrounds.json.
-- Alternative to running load_to_supabase.mjs for just this data — no
-- service-role key needed, since the SQL Editor already runs with full
-- privileges. Safe to re-run any time; upserts on (name, source) /
-- updates by name, same as the loader's own behavior.

-- Feats: 1 SRD 5.1 entry (Grappler) -> 17 entries from SRD 5.2 (2024).
insert into feats (name, source, prerequisite, description, benefits) values ('Grappler', 'srd', 'Strength or Dexterity 13+', '(General feat) You gain the following benefits.
**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.
**Punch and Grab.** When you hit a creature with an Unarmed Strike as part of the Attack action on your turn, you can use both the Damage and the Grapple option. You can use this benefit only once per turn.
**Attack Advantage.** You have Advantage on attack rolls against a creature Grappled by you.
**Fast Wrestler.** You don''t have to spend extra movement to move a creature Grappled by you if the creature is your size or smaller.', '["(General feat) You gain the following benefits.", "**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.", "**Punch and Grab.** When you hit a creature with an Unarmed Strike as part of the Attack action on your turn, you can use both the Damage and the Grapple option. You can use this benefit only once per turn.", "**Attack Advantage.** You have Advantage on attack rolls against a creature Grappled by you.", "**Fast Wrestler.** You don''t have to spend extra movement to move a creature Grappled by you if the creature is your size or smaller."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Alert', 'srd', NULL, '(Origin feat) You gain the following benefits.
**Initiative Proficiency.** When you roll Initiative, you can add your Proficiency Bonus to the roll.
**Initiative Swap.** Immediately after you roll Initiative, you can swap your Initiative with the Initiative of one willing ally in the same combat. You can''t make this swap if you or the ally has the Incapacitated condition.', '["(Origin feat) You gain the following benefits.", "**Initiative Proficiency.** When you roll Initiative, you can add your Proficiency Bonus to the roll.", "**Initiative Swap.** Immediately after you roll Initiative, you can swap your Initiative with the Initiative of one willing ally in the same combat. You can''t make this swap if you or the ally has the Incapacitated condition."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Magic Initiate', 'srd', NULL, '(Origin feat) You gain the following benefits.
**Two Cantrips.** You learn two cantrips of your choice from the Cleric, Druid, or Wizard spell list. Intelligence, Wisdom, or Charisma is your spellcasting ability for this feat''s spells (choose when you select this feat).
**Level 1 Spell.** Choose a level 1 spell from the same list you selected for this feat''s cantrips. You always have that spell prepared. You can cast it once without a spell slot, and you regain the ability to cast it in that way when you finish a Long Rest. You can also cast the spell using any spell slots you have.
**Spell Change.** Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.
You can take this feat more than once, but you must choose a different spell list each time.', '["(Origin feat) You gain the following benefits.", "**Two Cantrips.** You learn two cantrips of your choice from the Cleric, Druid, or Wizard spell list. Intelligence, Wisdom, or Charisma is your spellcasting ability for this feat''s spells (choose when you select this feat).", "**Level 1 Spell.** Choose a level 1 spell from the same list you selected for this feat''s cantrips. You always have that spell prepared. You can cast it once without a spell slot, and you regain the ability to cast it in that way when you finish a Long Rest. You can also cast the spell using any spell slots you have.", "**Spell Change.** Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.", "You can take this feat more than once, but you must choose a different spell list each time."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Savage Attacker', 'srd', NULL, '(Origin feat) You''ve trained to deal particularly damaging strikes. Once per turn when you hit a target with a weapon, you can roll the weapon''s damage dice twice and use either roll against the target.', '["(Origin feat) You''ve trained to deal particularly damaging strikes. Once per turn when you hit a target with a weapon, you can roll the weapon''s damage dice twice and use either roll against the target."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Skilled', 'srd', NULL, '(Origin feat) You gain proficiency in any combination of three skills or tools of your choice.
You can take this feat more than once.', '["(Origin feat) You gain proficiency in any combination of three skills or tools of your choice.", "You can take this feat more than once."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Ability Score Improvement', 'srd', 'Level 4+', '(General feat) Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can''t increase an ability score above 20.
You can take this feat more than once.', '["(General feat) Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can''t increase an ability score above 20.", "You can take this feat more than once."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Archery', 'srd', 'Fighting Style feature', '(Fighting Style feat) You gain a +2 bonus to attack rolls you make with Ranged weapons.', '["(Fighting Style feat) You gain a +2 bonus to attack rolls you make with Ranged weapons."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Defense', 'srd', 'Fighting Style feature', '(Fighting Style feat) While you''re wearing Light, Medium, or Heavy armor, you gain a +1 bonus to Armor Class.', '["(Fighting Style feat) While you''re wearing Light, Medium, or Heavy armor, you gain a +1 bonus to Armor Class."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Great Weapon Fighting', 'srd', 'Fighting Style feature', '(Fighting Style feat) When you roll damage for an attack you make with a Melee weapon that you are holding with two hands, you can treat any 1 or 2 on a damage die as a 3. The weapon must have the Two-Handed or Versatile property to gain this benefit.', '["(Fighting Style feat) When you roll damage for an attack you make with a Melee weapon that you are holding with two hands, you can treat any 1 or 2 on a damage die as a 3. The weapon must have the Two-Handed or Versatile property to gain this benefit."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Two Weapon Fighting', 'srd', 'Fighting Style feature', '(Fighting Style feat) When you make an extra attack as a result of using a weapon that has the Light property, you can add your ability modifier to the damage of that attack if you aren''t already adding it to the damage.', '["(Fighting Style feat) When you make an extra attack as a result of using a weapon that has the Light property, you can add your ability modifier to the damage of that attack if you aren''t already adding it to the damage."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Boon of Combat Prowess', 'srd', 'Level 19+', '(Epic Boon feat) You gain the following benefits.
**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.
**Peerless Aim.** When you miss with an attack roll, you can hit instead. Once you use this benefit, you can''t use it again until the start of your next turn.', '["(Epic Boon feat) You gain the following benefits.", "**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.", "**Peerless Aim.** When you miss with an attack roll, you can hit instead. Once you use this benefit, you can''t use it again until the start of your next turn."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Boon of Dimensional Travel', 'srd', 'Level 19+', '(Epic Boon feat) You gain the following benefits.
**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.
**Blink Steps.** Immediately after you take the Attack action or the Magic action, you can teleport up to 30 feet to an unoccupied space you can see.', '["(Epic Boon feat) You gain the following benefits.", "**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.", "**Blink Steps.** Immediately after you take the Attack action or the Magic action, you can teleport up to 30 feet to an unoccupied space you can see."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Boon of Fate', 'srd', 'Level 19+', '(Epic Boon feat) You gain the following benefits.
**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.
**Improve Fate.** When you or another creature within 60 feet of you succeeds on or fails a D20 Test, you can roll 2d4 and apply the total rolled as a bonus or penalty to the d20 roll. Once you use this benefit, you can''t use it again until you roll Initiative or finish a Short or Long Rest.', '["(Epic Boon feat) You gain the following benefits.", "**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.", "**Improve Fate.** When you or another creature within 60 feet of you succeeds on or fails a D20 Test, you can roll 2d4 and apply the total rolled as a bonus or penalty to the d20 roll. Once you use this benefit, you can''t use it again until you roll Initiative or finish a Short or Long Rest."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Boon of Irresistible Offense', 'srd', 'Level 19+', '(Epic Boon feat) You gain the following benefits.
**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.
**Overcome Defenses.** The Bludgeoning, Piercing, and Slashing damage you deal always ignores Resistance.
**Overwhelming Strike.** When you roll a 20 on the d20 for an attack roll, you can deal extra damage to the target equal to the ability score increased by this feat. The extra damage''s type is the same as the attack''s type.', '["(Epic Boon feat) You gain the following benefits.", "**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.", "**Overcome Defenses.** The Bludgeoning, Piercing, and Slashing damage you deal always ignores Resistance.", "**Overwhelming Strike.** When you roll a 20 on the d20 for an attack roll, you can deal extra damage to the target equal to the ability score increased by this feat. The extra damage''s type is the same as the attack''s type."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Boon of Spell Recall', 'srd', 'Level 19+', '(Epic Boon feat) You gain the following benefits.
**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.
**Free Casting.** Whenever you cast a spell with a level 1–4 spell slot, roll 1d4. If the number you roll is the same as the slot''s level, the slot isn''t expended.', '["(Epic Boon feat) You gain the following benefits.", "**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.", "**Free Casting.** Whenever you cast a spell with a level 1\u20134 spell slot, roll 1d4. If the number you roll is the same as the slot''s level, the slot isn''t expended."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Boon of the Night Spirit', 'srd', 'Level 19+', '(Epic Boon feat) You gain the following benefits.
**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.
**Merge with Shadows.** While within Dim Light or Darkness, you can give yourself the Invisible condition as a Bonus Action. The condition ends on you immediately after you take an action, a Bonus Action, or a Reaction.
**Shadowy form.** While within Dim Light or Darkness, you have Resistance to all damage except Psychic and Radiant.', '["(Epic Boon feat) You gain the following benefits.", "**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.", "**Merge with Shadows.** While within Dim Light or Darkness, you can give yourself the Invisible condition as a Bonus Action. The condition ends on you immediately after you take an action, a Bonus Action, or a Reaction.", "**Shadowy form.** While within Dim Light or Darkness, you have Resistance to all damage except Psychic and Radiant."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;
insert into feats (name, source, prerequisite, description, benefits) values ('Boon of Truesight', 'srd', 'Level 19+', '(Epic Boon feat) You gain the following benefits.
**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.
**Truesight.** You have Truesight with a range of 60 feet.', '["(Epic Boon feat) You gain the following benefits.", "**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 30.", "**Truesight.** You have Truesight with a range of 60 feet."]'::jsonb)
  on conflict (name, source) do update set prerequisite = excluded.prerequisite, description = excluded.description, benefits = excluded.benefits;

-- Backgrounds: backfill the new origin_feat_name column.
update backgrounds set origin_feat_name = 'Magic Initiate' where name = 'Acolyte' and source = 'srd';
update backgrounds set origin_feat_name = 'Alert' where name = 'Criminal' and source = 'srd';
update backgrounds set origin_feat_name = 'Magic Initiate' where name = 'Sage' and source = 'srd';
update backgrounds set origin_feat_name = 'Savage Attacker' where name = 'Soldier' and source = 'srd';
